project:
  type: website

website:
  title: "Jae Yoon Cho"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: Research.qmd
        text: Research
      - href: Blog.qmd
        text: Blog
  page-footer:
    right: "&copy; 2024, Jae Yoon Cho"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

